# =========================
# Build stage
# =========================
FROM node:20-alpine AS build

WORKDIR /app

# Copia package.json dal context (frontend/)
COPY package*.json ./

RUN npm ci

# Copia tutto il frontend
COPY . .

RUN npm run build


# =========================
# Runtime stage
# =========================
FROM nginx:1.25-alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY deployment/frontend/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
