// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbkfnibaphesqccufuvy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdia2ZuaWJhcGhlc3FjY3VmdXZ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTQzODAsImV4cCI6MjA2OTk3MDM4MH0.-4YFPf4NJAvBGtWAqONptD3tIA_gBw3mZ5z40QojMrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});