// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ckgmnfmetrosjmjthwko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrZ21uZm1ldHJvc2ptanRod2tvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNjg2NDgsImV4cCI6MjA3MjY0NDY0OH0.H_7yowImUssfusUfSaFVQ6eg-l2kHWA3OwT4OxOfZzI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// NOTE: Database types are temporarily disabled because the connected
// Supabase project has no schema types yet. After we recreate/migrate
// the tables, we can re-enable typed client for full type safety.
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});